name: $(MajorVersion).$(MinorVersion).$(rev:r)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET 8.0"
    inputs:
      packageType: "sdk"
      version: "8.0.x"

  - task: DotNetCoreCLI@2
    displayName: "Restore app"
    inputs:
      command: "restore"
      projects: "**/*.csproj"
      feedsToUse: "select"
      vstsFeed: "7a124f36-f58f-4fba-83fa-320bd1c605a7"

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: "build"
      projects: "**/*.csproj"
      arguments: "--configuration $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "Pack"
    inputs:
      command: "pack"
      projects: "src/Microsoft.SyndicationFeed.ReaderWriter.csproj"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artofacts"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"

  - task: DotNetCoreCLI@2
    displayName: "Push"
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "7a124f36-f58f-4fba-83fa-320bd1c605a7"
